version: '3'

services:
  app:
    image: haashim-node-website:latest
    ports:
      - "3001:3000"
    networks:
      - app-network
    # volumes:
    #   - ./app:/usr/src/app
    #   - /usr/src/app/node_modules
networks:
  app-network:
    driver: bridge