version: '3'

services:
  app:
    image: haashim-node-website:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=mongodb://db:27017/posts

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge